//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEFE.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercis
    {
        public int id_exercise { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string solucion { get; set; }
        public Nullable<int> fk_lessons { get; set; }
    
        public virtual lesson lesson { get; set; }
    }
}
