//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEFE.Conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEFEEntities : DbContext
    {
        public ProyectoEFEEntities()
            : base("name=ProyectoEFEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cur> curs { get; set; }
        public virtual DbSet<exercis> exercises { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<topic> topics { get; set; }
    }
}
